### ISSUE TITLE
organizations grapql query for the default auth model fails

### ISSUE THREAD

**Issue by dalehille** [razee-io/Razeedash-api#421]
An error is returned when making a call to the `organizations` endpoint using an x-api-key header

```query {
  organizations {
    _id,
    name
  }
}
```

returns:
```
{"errors":[{"message":"Cannot read property 'findOne' of undefined","locations":[{"line":2,"column":3}],"path":["organizations"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'findOne' of undefined","    at Function.UserDefaultSchema.statics.getOrgs (/usr/src/app/apollo/models/user.default.schema.js:142:40)","    at organizations (/usr/src/app/apollo/resolvers/organization.js:37:26)","    at field.resolve (/usr/src/node_modules/graphql-extensions/dist/index.js:134:26)","    at field.resolve (/usr/src/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)","    at resolveFieldValueOrError (/usr/src/node_modules/graphql/execution/execute.js:467:18)","    at resolveField (/usr/src/node_modules/graphql/execution/execute.js:434:16)","    at executeFields (/usr/src/node_modules/graphql/execution/execute.js:275:18)","    at executeOperation (/usr/src/node_modules/graphql/execution/execute.js:219:122)","    at executeImpl (/usr/src/node_modules/graphql/execution/execute.js:104:14)","    at Object.execute (/usr/src/node_modules/graphql/execution/execute.js:64:35)","    at /usr/src/node_modules/apollo-server-core/dist/requestPipeline.js:249:48","    at Generator.next (<anonymous>)","    at /usr/src/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)","    at __awaiter (/usr/src/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)","    at execute (/usr/src/node_modules/apollo-server-core/dist/requestPipeline.js:228:20)"]}}}],"data":{"organizations":null}}
```

**Comment by dalehille** [comment]
1. in resolvers/organization.js `models` should be passed as a parameter.  or the getOrgs function in user.default.schema.js should get models from `context`

2.  UserDefaultSchema.statics.getOrgs should be updated to read from `meFromDB.orgs` after https://github.com/razee-io/Razeedash-api/pull/414 and https://github.com/razee-io/Razeedash/pull/319 are merged
