### ISSUE TITLE
razeedash-api logging errors when a channel is not found

### ISSUE THREAD

**Issue by dalehille** [razee-io/Razeedash-api#840]
```
ReferenceError: Cannot access 'channel_uuid' before initialization\n    at Object.channelVersion (/home/node/app/apollo/resolvers/channel.js:148:140)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async channelVersionByName (/home/node/app/apollo/resolvers/channel.js:127:14)"},
```

**Comment by tasneem067** [comment]
#851

**Comment by tasneem067** [comment]
Resolved
